name: Obfuscate BPB
on:
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull official repo & copy
        run: |
          git clone --depth 1 https://github.com/bia-pain-bache/BPB-Worker-Panel.git bpbtmp
          cp bpbtmp/_worker.js origin.js
      - name: Obfuscate
        run: npx javascript-obfuscator origin.js --output _worker.js
      - name: Push back
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add _worker.js origin.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto obfuscate" && git push)
